### PR TITLE
install revive on `make get` to ensure we have the correct version

### PR DESCRIPTION
**Pull request by amery**
and fix some easy problems

### CODE REVIEW

**Review by karasz — APPROVED** [review]
Not a fan of breaking function definition lines (I don't think that it improves legibility and comprehension).  Also not a fan of ignoring errors from Close, but in this case I have no better alternative since not ignoring them will cause false errors :(. "Approving" as it is.

**Comment by amery** [comment]
I would say in this case Close errors are handled by the workflow. when we reach the point of ignoring them we already know their are already closed, or have never been used, or we are about to exit()

**Comment by amery** [comment]
The worst part to me of breaking the definition line is that we aren't allowed to add extra whitespace to separate the second half of it from the content of the functions.

Alternative is to reduce the token lengths, but that doesn't improve readability either

**Comment by amery** [comment]
v0.0.4 tagged

**Pull request merged**
